development:
  adapter: postgresql
  encoding: utf8
  database: hehastwoeyes_development
  pool: 5
  username: renoliver
  host: localhost
#  template: template0

test:
  adapter: postgresql
  encoding: utf8
  database: hehastwoeyes_test
  pool: 5
  username: renoliver
  min_messages: WARNING
  host: localhost
#  template: template0
